#!/usr/bin/env sh
mv new_computing_publication_list.bib computing_publication_list.bib
mv new_experiment_publication_list.bib experiment_publication_list.bib
mv new_physics_publication_list.bib physics_publication_list.bib
mv new_short_computing_publication_list.bib short_computing_publication_list.bib
mv new_short_physics_publication_list.bib short_physics_publication_list.bib
mv new_shortest_computing_publication_list.bib shortest_computing_publication_list.bib
mv new_shortest_physics_publication_list.bib shortest_physics_publication_list.bib